### ISSUE TITLE
TypeError: Cannot read property 'modes' of undefined

### ISSUE THREAD

**Issue by OR13** [digitalbazaar/x25519-key-pair#7]
See https://github.com/digitalbazaar/did-method-key-js/issues/23

**Comment by mattcollier** [comment]
@dmitrizagidulin @OR13 can either of you provide specifics about how we can get this resolved?

**Comment by OR13** [comment]
Per the link in the comment: https://github.com/digitalbazaar/did-method-key-js/issues/23#issuecomment-625956530

Its possible that later versions of did-key fixed this issue, and its now stale.

I have since implemented by own version of did-key and this key library, so feel free to close this issue when ever.

**Comment by dmitrizagidulin** [comment]
Thanks, closing!
